---
title: "MeganticTraits_Species~Traits" 
author: "Julie Messier" 
output: 
   pdf_document:
      toc: true
      toc_depth: 3
      fig_width: 5
      fig_height: 4
date: '`r Sys.Date()`'
---



```{r,include=FALSE}
#<<LIBRARIES>>
library(car) # for powerTransform
library(vegan) # for decostand (standardizing data)
library(tree) # for tree()
library(MASS) # for glm.nb()  
library(mgcv) # for gam()
library(MuMIn)

wrk.dir<-("C:/Users/Julie/Desktop/Postdoc/PROJECT - Megantic Traits/Workspaces/") # Workspaces
data.dir<-(("C:/Users/Julie/Desktop/Postdoc/PROJECT - Megantic Trait/Data/")) # data
res.dir<-("C:/Users/Julie/Desktop/Postdoc/PROJECT - Megantic Traits/Results/")  # Results
grp.dir<-("C:/Users/Julie/Desktop/Postdoc/PROJECT - Megantic Trait/Graphs/")   # Graphs
fct.dir<-("C:/Users/Julie/Desktop/Postdoc/PROJECT - Megantic Trait/Functions/") # Functions

```    

```{r,echo=F,eval=T, include=FALSE}
#<<LOAD FILES>>

#U.traits4.sp
load(file=paste0(wrk.dir,'Species-Level.Traits.Understory-Layer.with.MycFrac.and.SeedSize.and.PCs.RData')) 
dim(U.traits4.sp)

# U.Ys.c
load(file=paste0(wrk.dir,'All.Response.variables.Understory.Layer.Inf.removed.RData')) 
dim(U.Ys.c)

# subset abundance data to include only the species with trait data 
    sp.response<-U.Ys.c[rownames(U.Ys.c)%in%rownames(U.traits4.sp),]
    dim(sp.response)
    
# subset trait data to include only the species with abundance data
Xs<-U.traits4.sp[rownames(U.traits4.sp)%in%rownames(U.Ys.c),]
dim(Xs)

# Create long and short lists of traits 
    Trait.Names.8t<-c("Log.Ht.veg","Max.Root.Loca","Log.Lamina.thck","LDMC","Log.Leaf.Area",  
                        "Leaf.Mass.Frac","SRL","Myc.Frac")
    length(which(complete.cases(Xs[,Trait.Names.8t])))
      # 36 species
    
    Trait.Names.5t<-c("Log.Ht.veg","Log.Lamina.thck","LDMC","Log.Leaf.Area","Leaf.Mass.Frac")
    length(which(complete.cases(Xs[,Trait.Names.5t])))
      # 46 species
    
Xs<-U.traits4.sp[rownames(U.traits4.sp)%in%rownames(U.Ys.c),]
```

#(A) Abundance vs 8 Traits

## A1 - Explore Trait Interactions
   
### A1.1 - Regression Tree
   
```{r,echo=F,eval=T}
   
    par(mfrow=c(1,1))
    tree.model.abund<-tree(sp.response$abundance.ratio~.,data=Xs[,Trait.Names.8t],
                     control=tree.control(nobs=36,mincut=3))
    plot(tree.model.abund); text(tree.model.abund);title('Regression Tree \n Abundance.ratio vs 8 traits')
      # Myc.frac is most important variable       # for sp. with high myc.frac, SRL matters
 
    tree.model.abund
```    
Deviance explained:
```{r,echo=T}
  1-(deviance(tree.model.abund)/178.1) 
```
=======

 SUMMARY

 significant trait-trait interactions to include in full model: 

    * SRL:Myc.Frac 
    * Log.Leaf.Area:SRL
    * Log.Ht.veg:Max.Root.Loca 
    * Max.Root.Loca:Leaf.Mass.Frac
    * Log.Ht.veg:SRL
    * Max.Root.Loca:SRL 
    * LDMC:SRL
========
